version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_NAME=passlockerDB
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=passlockerDB
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: